package main

import "belajar-golang-dasar/src"

func main() {
	/* List Materi */
	// src.HelloWorld()
	// src.Number()
	// src.Boolean()
	// src.String()
	// src.Variable()
	// src.Constant()
	// src.Conversion()
	// src.TypeDeclaration()
	// src.MathOperations()
	// src.ComparationOperator()
	// src.BooleanOperator()
	// src.Array()
	// src.Slice()
	// src.Map()
	// src.IfExpression()
	// src.SwitchExpression()
	// src.For()
	// src.BreakContinue()
	// src.Function()
	// src.FunctionParameter()
	// src.FunctionReturnValue()
	// src.FunctionReturnMultipleValue()
	// src.FunctionReturnNamedValue()
	// src.FunctionVariadic()
	// src.FunctionAsValue()
	// src.FunctionAsParameter()
	// src.FunctionAnonymous()
	// src.FunctionRecursive()
	// src.Closure()
	// src.Defer()
	// src.Panic()
	// src.Recover()
	src.Comment()
}
