name: deploy-master

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: 1.19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go {{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: {{ matrix.go-version }}
      - name: Installing dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with Go CLI
        run: go test